let lang = `en-US`;

let c = require(`../config.js`);
let e = c.emojis;

module.exports = class {
    constructor() {
        this.language = {
            UTILS: {
                ERROR_TITLE: `ERREUR`,
                ERROR_MESSAGE: `${e.servererror} An internal error has occurred, please try again later.`,
                ERROR: (error) => `Here is the error code, please report it to the bot staff team.\n\`\`\`${error}\`\`\``,
                NO_ENABLED: `${e.error} Sorry this command is not available now, please try again later.`,
                STAFF_ONLY: `${e.error} Sorry this command is reserved for the bot staff team.`,
                OWNER_ONLY: `${e.error} Sorry this command is reserved for the server owner.`,
                NSFW: `${e.error} Sorry but this is an NSFW content command, so it must be done in an NSFW channel.`,
                NO_PERMISSION_CLIENT: (permission) => `${e.error} I do not have the following permission(s) : \n\`\`${permission}\`\``,
                NO_PERMISSION_USER: (permission) => `${e.error} You do not have the following permission(s) : \n\`\`${permission}\`\``,
                NO_GUILD_PREMIUM: `${e.error} Sorry, this command is only for **premium** servers.`,
                NO_GUILD_PREMIUM_GOLD: `${e.error} Sorry, this command is only for **premium gold** servers.`,
                NO_PREMIUM_HOW_TO: `To get the premium, you just have to join the support server and go to the #premium channel.`,
                NOT_FOUND: `${e.error} Désolé, cette commande n'existe pas.`,
                SLOWMODE: (slowmode, command) => `${e.time} You have to wait ${slowmode} second (s) before you can execute the command \`\`${command}\`\` again.`,
                ENABLED: `${e.success} Enabled`,
                DISABLED: `${e.error} Disabled`,
                NOT_DEFINED: `${e.error} Undefined`,
                NONE: `${e.error} None`,
                YES: `${e.success} Yes`,
                NO: `${e.error} No`,
                DEFAULT_PREFIX: (prefix) => `Hey, my prefix on this server is \`\`${prefix}\`\``,
                WRONG_CHANNEL: (id) => `This channel is not a channel to execute commands, please go to the channel <#${id}>.`,
                MONTHS_SHORT: [
                    `Jan`,
                    `Feb`,
                    `March`,
                    `Apr`,
                    `May`,
                    `June`,
                    `July`,
                    `Aug`,
                    `Sept`,
                    `Oct`,
                    `Nov`,
                    `Dec`
                ],
                REGIONS: {
                    'us-west': `Western United States`,
                    'us-east': `Eastern United States`,
                    'us-central': `Central United States`,
                    'us-south': `Southern United States`,
                    singapore: `Singapore`,
                    southafrica: `South Africa`,
                    sydney: `Sidney`,
                    europe: `Europe`,
                    brazil: `Brasil`,
                    hongkong: `HongKong`,
                    russia: `Russia`,
                    japan: `Japan`,
                    india: `India`,
                    dubai: `Dubai`,
                    amsterdam: `Amsterdam`,
                    london: `London`,
                    frankfurt: `Frankfurt`,
                    'eu-central': `Central Europe`,
                    'eu-west': `Western Europe`,
                },
                VERIFICATION_LEVELS: {
                    NONE: `None (0/4)`,
                    LOW: `Low (1/4)`,
                    MEDIUM: `Medium (2/4)`,
                    HIGH: `(╯°□°）╯︵  ┻━┻ (3/4)`,
                    VERY_HIGH: `┻━┻ミヽ(ಠ益ಠ)ノ彡┻━┻ (4/4)`
                },
            },
            EVENTS: {
                CHANNEL_CREATE: (channel, name) => `${e.plus} Channel created : ${channel} (${name})`,
                CHANNEL_DELETE: (name) => `${e.minus} Channel deleted : ${name}`,
                CHANNEL_UPDATE: `${e.edit} Channel renamed`,
                OLD_NAME: `Old name :`,
                NEW_NAME: `New name :`,
                EMOJI_CREATE: (name) => `Emoji created : ${name}`,
                EMOJI_DELETE: (name) => `Emoji deleted : ${name}`,
                EMOJI_UPDATE: `Emoji renamed`,
                GUILD_MEMBER_UPDATE: `Member renamed`,
                GUILD_UPDATE: `Server renamed`,
                MESSAGE_DELETE: (channel, author, username) => `${e.minus} Message from ${author} (${username}) has been deleted in ${channel}`,
                MESSAGE_DELETE_CONTENT: `Message content :`,
                MESSAGE_UPDATE: `${e.edit} Messages edited`,
                OLD_CONTENT: `Old message :`,
                NEW_CONTENT: `New message :`,
                ROLE_CREATE: (role, name) => `${e.plus} Role created : ${role} (${name})`,
                ROLE_DELETE: (name) => `${e.minus} Role deleted : ${name}`,
                ROLE_UPDATE: `${e.edit} Role renamed`,
            },
            HELP: {
                DESCRIPTION: `Allows you to get the bot's help page and help for commands`,
                USAGE: `$help`,
                EXAMPLES: `$help`,
                HEADINGS: [
                    `Help on the command : `,
                    `${e.desc2} Description :`,
                    `${e.folder} Category :`,
                    `${e.help} Usage :`,
                    `${e.search} Examples :`,
                    `${e.add} Aliases :`,
                    `${e.crown} Permissions :`,
                    `Bot`,
                    `User`,
                    `Here is the list of available commands :`,
                ],
                FOOTER: (username) => `${username} | Version : ${c.version}`,
            },
            CATEGORIES: {
                MODERATION: `🛡️ Moderation`,
                BOT: `🤖 Botinfos`,
                CONFIGURATION: `🛠️ Configuration`,
                INVITES: `📎 Invitation`,
                GAMES: `🎮 Games`,
                ROLEPLAY: `🎭 Roleplay`,
                UTILS: `🧰 Tools`,
                IMAGES: `📷 Images`,
                STAFF: `STAFF`,
                PREMIUM: `👑 Custom command`,
            },
            ADDBOT: {
                DESCRIPTION: `Allows you to get the bot invitation link.`,
                USAGE: `$addbot`,
                EXAMPLES: `$addbot`,
                TITLE: `Here are the links to invite our dear Amandine.`,
                CLICK: `Click here.`,
                NO_PERM: `No permissions.`,
                MEMBER_PERM: `Member Permissions.`,
                MOD_PERM: `Moderation Permissions.`,
                ADMIN_PERM: `Administration Permissions.`,
            },
            BOTINFOS: {
                DESCRIPTION: `Displays information about the bot.`,
                USAGE: `$botinfos`,
                EXAMPLES: `$botinfos`,
                TITLE: (botName) => `**Statistics of ${botName}**\n[Support server](${c.supportServer}) | [Translations](${c.translateGithub}) | [Support me](https://www.buymeacoffee.com/amandine)`,
                OWNER: `${e.crown} | Owner`,
                VERSION: `${e.bot} | Bot version`,
                DATE: `${e.calendar} | Creation date`,
                USERS: `${e.users} | Users`,
                GUILDS: `${e.server} | Servers`,
                CHANNELS: `${e.channels} | Channels`,
                PING: `${e.latency} | Latency`,
                RAM: `${e.ram} | RAM`,
                UPTIME: `${e.time} | Temp since last restart`,
                CURRENT: `_Current`,
            },
            MYCOLOR: {
                DESCRIPTION: `Allows you to choose the color of the bot embeds.`,
                USAGE: `$mycolor <hexadecimal color>`,
                EXAMPLES: `$mycolor #FFFFFF\n$mycolor reset`,
                RESET: `${e.success} Your color has been reset to \`\`Random\`\`.`,
                MOREINFOS: `Click here fr more infos.`,
                NO_ARGS: `${e.error} Please specify an hexadecimal color.`,
                NO_HEX: `${e.error} It is not a valid hexadecimal color.`,
                SUCCESS: (color) => `${e.success} Your color has been changed to \`\`${color}\`\``,
            },
            PING: {
                DESCRIPTION: `Allows you to see the latency of the bot and the discord API.`,
                USAGE: `$ping`,
                EXAMPLES: `$ping`,
                FETCHING: `${e.loading} Calculation in progress ...`,
                SLOW: `The bot is slow.`,
                FAST: `The bot is fast.`,
                PING: (api, bot, hint) => `${e.server} API : ***${api}*** ms\n${e.bot} BOT : ***${bot}*** ms\n\n${hint}\n[Discord Status](https://status.discord.com/)` //\n:rofl: Database : ${db}
            },
            INFOCONFIG: {
                DESCRIPTION: `Allows you to see the current configuration of the bot settings on the server.`,
                USAGE: `$viewconfiguration <option>`,
                EXAMPLES: `$viewconfiguration\n$viewconfiguration logs`,
                LOG_TITLE: `Here is the configuration of the logs on this server.`,
                LOG_STATUS: `Log status :`,
                LOG_CHANNEL: `Log channel :`,
                LOG_ACTIVE: `Logs enabled :`,
                LOG_INACTIVE: `Logs disabled :`,
                INFO: `Here is the current server configuration.`,
                PREFIX: `Prefix`,
                LANG: `Lang`,
                CLEANIFY: `Clean mode`,
                JOINMSGISON: `Welcome message status :`,
                LEAVEMSGISON: `Goodbye message status :`,
                JOINCHANNEL: `Welcome channel :`,
                LEAVECHANNEL: `Goodbye channel :`,
                JOINMSG: `Welcome message :`,
                LEAVEMSG: `Goodbye message :`,
                LOGS_TIP: `Log details $configuration logs`,
                LOGS_DETAILS: `Detailed list of logs.`,
                LOGS_LIST: `**Here are the parameters of the server logs.**`,
                LOGS_STATE: `**Log status :**`,
                LOGS_CHANNEL: `**Log channel :**`,
                NO_LOGS_CHANNEL: `The channel is not configured or is invalid.`,
                LOGS_ACTIVE: `Logs enabled :`,
                LOGS_INACTIVE: `Logs disabled :`,
            },
            LOGGING: {
                DESCRIPTION: `Allows you to define which logs you want to activate or not.`,
                USAGE: `$logging <setting> <on/off>`,
                EXAMPLES: `$logging messageUpdate on\n$logging guildUpdate off\n$logging all on\n$logging channel #canal\n$logging off`,
                LIST: `**Voici la liste des logs configurables.**`,
                NO_PARAM: `${e.error} Please specify a log to configure.`,
                NO_STATUS: `${e.error} Please specify a status : on/off.`,
                INVALID: `${e.error} This log is invalid`,
                ALREADY_ENABLED: `${e.error} Ce log est déjà activé.`,
                LOG_ENABLED: (log) => `${e.success} The log ${log} has been enabled.`,
                ALREADY_DISABLED: `${e.error} This log is already enabled.`,
                LOG_DISABLED: (log) => `${e.success} The log ${log} has been disabled.`,
                ALL_ENABLED: `${e.success} All the logs have been enabled.`,
                ALL_DISABLED: `${e.success} All the logs have been deactivated.`,
                ENABLED: `${e.success} The logs have been enabled.`,
                DIASBLED: `${e.success} The logs have been deactivated.`,
                INVALID_CHANNEL: `${e.error} Please specify a valid channel on the server.`,
                SUCCESS_CHANNEL: `${e.success} The log channel has been configured correctly.`,
                INVALID_OR_NULL_CHANNEL: `${e.error} Please check that you have correctly configured a log channel or that the one you have configured is valid before activating the logs.`,
                NO_PERM: `${e.error} Please give me the permission to post in this channel or specify a different one.`
            },
            BACKUP: {
                DESCRIPTION: `Allows you to create backups of your servers.`,
                USAGE: `$backup <option> [name]`,
                EXAMPLES: `$backup create name\n$backup load name\n$backup infos name\n$backup remove name\n$backup list`,
                LIMIT_REACHED: `${e.success} You have reached the maximum limit for backups, you can always request a few more from the support server.`,
                NO_NAME: `${e.error} Please specify a name for the backup.`,
                ENTRY_ALREADY_EXIST: `${e.success} There is already a backup saved with this name.`,
                NO_ENTRY: `${e.error} There are no saved backup with this name.`,
                START_BACKUP_SAVE: `${e.loading} The backup has started, please wait.`,
                BACKUP_SAVE_DONE: `${e.success} The backup is complete. You can now load it wherever you want.`,
                ROLE_NOT_HIGHEST: `${e.success} Please check that my role is at the top of the list and that I have maximum permissions to be able to load the save.`,
                START_BACKUP_LOAD_CONFIRM: `Please confirm that you are sure you want to load the backup, everything will be deleted from the server. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                START_BACKUP_LOAD: `${e.loading} The backup is being installed on the server.`,
                BACKUP_LOAD_CANCEL: `${e.error} The backup installation was canceled.`,
                BACKUP_LOAD_DONE: `${e.success} The backup has been installed, enjoy your brand new server.`,
                LOAD_TIMEOUT: `${e.time} The time is up, you have not comfirmed that you want to load the save.`,
                INFOS_TITLE: `Backup information.`,
                INFOS_NAME: `Name :`,
                INFOS_ID: `ID :`,
                INFOS_SERVER_NAME: `Server name :`,
                INFOS_SERVER_ID: `Server ID :`,
                INFOS_SIZE: `Size :`,
                INFOS_DATE: `Creation date :`,
                BACKUP_DELETE_CONFIRM: `${e.loading} Please confirm that you are sure you want to delete the backup. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                BACKUP_DELETE_CANCEL: `${e.error} The backup deletion was canceled.`,
                BACKUP_DELETE_DONE: `${e.success} The backup has been deleted.`,
                DELETE_TIMEOUT: `${e.time} The time is up, you have not comfirmed that you want to delete the backup.`,
                NO_BACKUPS: `${e.error} You have no server backups yet.`,
                LIST: `Here is the list of your backups :`,
                NO_ACTION: `${e.error} Please specify an action: create, load, infos, remove, list.`,
            },
            JOINMSG: {
                DESCRIPTION: `Allows you to configure the server welcome message and channel.`,
                USAGE: `$setjoin <option> <argument> `,
                EXAMPLES: `$setjoin on\n$setjoin off\n$setjoin reset\n$setjoin channel <mention>\n$setjoin message <message>\n$setjoin options`,
                OPTIONS_TITLE: `Here are the available settings for the welcome message.`,
                OPTIONS: `**{user}**-User mention\n**{user.name}**-Username\n**{user.tag}**-Username + tag\n**{user.createdat}**-The date the user's account was created\n**{user.id}**-User id\n**{guild}**-The name of the server\n**{guild.count}**-The number of members on the server\n**{inviter}**-The mention of the user who invited him\n**{inviter.tag}**-The name + tag of the user who invited him\n**{inviter.name}**-The name of the user who invited him\n**{inviter.id}**-The id of the user who invited him\n**{inviter.invites}**-The number of invitations of the user who invited him\n**{invite.code}**-The invitation code used\n**{invite.uses}**-The number of uses of the invitation\n**{invite.url}**-The URL of the invitation`,
                ALREADY_ENABLED: `${e.success} The welcome message is already enabled.`,
                CHANNEL_NOT_SET: `${e.error} Cannot activate welcome message until welcome channel is configured or invalid.`,
                MESSAGE_NOT_SET: `${e.error} Cannot activate the welcome message until the message is configured.`,
                ENABLED: `${e.success} The welcome message has been enabled.`,
                DISABLED: `${e.success} The welcome message has been disabled.`,
                ALREADY_DISABLED: `${e.success} The welcome message is already disabled.`,
                CONFIRM_RESET: `${e.loading} Please confirm that you are sure you want to reset the welcome message configuration. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                CANCELLED: `${e.success} The welcome message configuration reset has been canceled.`,
                RESET_SUCCESS: `${e.success} The configuration of the welcome message has been reinitialized.`,
                TIMEOUT: `${e.time} The time is up, you have not comfirmed that you want to reset the configuration of the welcome message.`,
                NO_MENTION: `${e.error} Please mention a channel.`,
                CHANNEL_SUCCESS: `${e.success} The welcome channel has been configured correctly.`,
                NO_ARGS_MESSAGE: (prefix) => `${e.error} Please specify a message. You can find the available settings with ${prefix}setjoin options.`,
                NON_EXISTENT_CHANNEL: `${e.error} Unable to configure welcome message until channel is configured or invalid.`,
                TOO_LONG: `${e.error} Your welcome message is too long, it must not exceed 1000 characters.`,
                MESSAGE_SUCCESS: `${e.success} The welcome message has been configured correctly.`,
                NO_ARGS: `${e.error} Please specify an action: on, off, reset, channel, message, options.`,
                NO_PERM: `${e.error} Please give me the permission to post in this channel or specify a different one.`,
            },
            LEAVEMSG: {
                DESCRIPTION: `Allows you to configure the server's goodbye message and channel.`,
                USAGE: `$setleave <option> <argument> `,
                EXAMPLES: `$setleave on\n$setleave off\n$setleave reset\n$setleave channel <mention>\n$setleave message <message>\n$setleave options`,
                OPTIONS_TITLE: `Here are the settings available for the goodbye message.`,
                OPTIONS: `**{user}**-User mention\n**{user.name}**-Username\n**{user.tag}**-Username + tag\n**{user.createdat}**-The date the user's account was created\n**{user.id}**-User id\n**{guild}**-The name of the server\n**{guild.count}**-The number of members on the server\n**{inviter}**-The mention of the user who invited him\n**{inviter.tag}**-The name + tag of the user who invited him\n**{inviter.name}**-The name of the user who invited him\n**{inviter.id}**-The id of the user who invited him\n**{inviter.invites}**-The number of invitations of the user who invited him\n**{invite.code}**-The invitation code used\n**{invite.uses}**-The number of uses of the invitation\n**{invite.url}**-The URL of the invitation`,
                ALREADY_ENABLED: `${e.success} The goodbye message is already enabled.`,
                CHANNEL_NOT_SET: `${e.error} Cannot activate goodbye message until goodbye channel is configured or invalid.`,
                MESSAGE_NOT_SET: `${e.error} Unable to activate goodbye message until message is configured.`,
                ENABLED: `${e.success} The goodbye message has been enabled.`,
                DISABLED: `${e.success} The goodbye message has been disabled.`,
                ALREADY_DISABLED: `${e.success} The goodbye message is already disabled.`,
                CONFIRM_RESET: `${e.loading} Please confirm that you are sure you want to reset the goodbye message configuration. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                CANCELLED: `${e.success} The reset of the goodbye message configuration has been canceled.`,
                RESET_SUCCESS: `${e.success} Goodbye message configuration has been reset successfully.`,
                TIMEOUT: `${e.time} The time is up, you have not validated that you want to reset the configuration of the goodbye message.`,
                NO_MENTION: `${e.error} Please mention a channel.`,
                CHANNEL_SUCCESS: `${e.success} The goodbye channel has been configured successfully.`,
                NO_ARGS_MESSAGE: (prefix) => `${e.error} Please specify a message. You can find the available settings with ${prefix}setleave options.`,
                NON_EXISTENT_CHANNEL: `${e.error} Cannot configure goodbye message until channel is configured or invalid.`,
                TOO_LONG: `${e.error} Your goodbye message is too long, it must not exceed 1000 characters.`,
                MESSAGE_SUCCESS: `${e.success} The goodbye message has been configured correctly.`,
                NO_ARGS: `${e.error} Please specify an action: on, off, reset, channel, message, options.`,
                NO_PERM: `${e.error} Please give me the permission to post in this channel or specify a different one.`,
            },
            PREFIX: {
                DESCRIPTION: `Allows you to configure the bot prefix on the server.`,
                USAGE: `$prefix <new prefix>`,
                EXAMPLES: `$prefix !!\n$prefix ?`,
                TOO_LONG: `${e.error} The new prefix must not exceed 10 characters.`,
                NO_ARGS: `${e.error} Please specify a new prefix.`,
                SUCCESS: (prefix) => `${e.success} The new prefix is now: ${prefix}`,
            },
            LANG: {
                DESCRIPTION: `Allows you to configure the bot language.`,
                USAGE: `$lang <lang>`,
                EXAMPLES: `$lang english\n$lang fr-FR`,
                NO_ARGS: (langs) => `${e.error} Please specify a language. Here are those available: ${langs}`,
                INVALID_LANG: (langs) => `${e.error} Please specify a valid language. Here are those available: ${langs}`,
                SUCCESS: (lang) => `${e.success} The bot language is now set to: ${lang}`,
            },
            ADDBONUS: {
                DESCRIPTION: `Allows you to add bonus invitations to a user.`,
                USAGE: `$addbonus <amount> @member1 @member2 ....`,
                EXAMPLES: `$addbonus 10 @Mr¤KayJayDee @Alex`,
                NO_ARGS: `${e.error} Please specify a quantity to add.`,
                ARGS_IS_NAN: `${e.error} Please check the quantity specified. Note that it cannot be negative and must not exceed 100.`,
                IS_BOT: `${e.error} Cannot add a bonus to a bot.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                SUCCESS: `${e.success} The member(s) received their bonus. Note that blacklisted members have been ignored.`,
            },
            CLEARINVITES: {
                DESCRIPTION: `Allows you to delete all invitations for a member or for all members.`,
                USAGE: `$clearinvites [@membre]`,
                EXAMPLES: `$clearinvites @Mr¤KayJayDee`,
                CONFIRM_ALL: `${e.loading} Please confirm that you are sure you want to reset invitations for all server members. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                CONFIRM_MEMBER: `${e.loading} Please confirm that you are sure you want to reset the invitations of the mentioned member(s). Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                CANCELLED_ALL: `${e.error} Resetting invitations for all members has been canceled.`,
                CANCELLED_MEMBER: `${e.error} The resetting of the invitations of the mentioned member(s) has been canceled.`,
                SUCCESS_ALL: `${e.success} All members invitations have been successfully reset.`,
                SUCCESS_MEMBER: `${e.success} The invitations of the mentioned member(s) have been successfully reset.`,
                TIMEOUT_ALL: `${e.time} The time is up, you have not validated that you want to reset the invitations of all the members of the server.`,
                TIMEOUT_MEMBER: `${e.time} The time is up, you have not validated that you want to reset the invitations of the mentioned member (s).`,
            },
            FETCHINVITES: {
                DESCRIPTION: `Allows to detect new invitations not saved in the cache.`,
                USAGE: `$fetchinvites`,
                EXAMPLES: `$fetchinvites`,
                SUCCESS: `${e.success} The invitations have been updated.`,
            },
            INVITEBLACKLIST: {
                DESCRIPTION: `Allows you to blacklist a member of the invitation system.`,
                USAGE: `$inviteblacklist <option> [@member]`,
                EXAMPLES: `$inviteblacklist add @membre\n$inviteblacklist remove @membre\n$inviteblacklist list`,
                NO_MENTION: `${e.error} Please mention a member.`,
                ALREADY_BLACKLISTED: `${e.error} This member is already blacklisted.`,
                ADD_SUCCESS: `${e.success} This member has been added to the blacklist.`,
                NOT_BLACKLISTED: `${e.error} This member is not blacklisted.`,
                REMOVE_SUCCESS: `${e.success} This member has been removed from the blacklist.`,
                NO_BLACKLISTED_USER: `${e.error} There are no blacklisted users.`,
                NO_ARGS: `${e.error} Please specify an action: add, remove, list`,
                LIST: `Here is the list of the blacklisted users`,
            },
            INVITERANK: {
                DESCRIPTION: `Allows you to configure the invitation rewards roles.`,
                USAGE: `$inviterank <option> <number of invitations> @role`,
                EXAMPLES: `$inviterank add 10 @Amandine-Lover\n$inviterank remove @Amandine-Lover`,
                NO_ARGS_INVITE: `${e.error} Please specify a number of invitations.`,
                IS_NAN: `${e.error} Please specify a valid number.`,
                ALREADY_RANK_FOR_INVITE: `${e.error} There is already a role for this number of invitations.`,
                NO_ROLE_MENTION: `${e.error} Please mention a role.`,
                INVALID_OR_MANAGED: `${e.error} Please verify that the role you mentioned is valid.`,
                ALREADY_INVITE_FOR_RANK: `${e.error} There are already a number of invitations for this role.`,
                ADD_SUCCESS: `${e.success} The role has been added.`,
                NO_ROLE_FOUND: `${e.error} There is no role of this name configured on the server.`,
                REMOVE_SUCCESS: `${e.success} The role has been deleted.`,
                NO_ARGS: `${e.error} Please specify an action: add, remove.`
            },
            INVITERANKS: {
                DESCRIPTION: `Allows you to see the server invitation rewards roles.`,
                USAGE: `$inviteranks`,
                EXAMPLES: `$inviteranks`,
                NO_RANKS: `${e.error} There is no role configured on the server.`,
                DELETED: (invite) => `${e.error} The role assigned to ${invite} invites has been deleted and is no longer accessible.\n`,
                RANKS: (role, invite) => `${role} (**${invite}** invites)\n`,
                RANK: `Here are the roles available`,
            },
            INVITES: {
                DESCRIPTION: `Allows you to see your invitations or those of a friend.`,
                USAGE: `$invites`,
                EXAMPLES: `$invites`,
                IS_BOT: `${e.error} Cannot see invitations from a bot.`,
                BLACKLISTED: `${e.error} You are blacklisted on this server, please contact a Moderator/Administrator.`,
                INVITES: (member, memberData, isYou, nextRank, role) => `${isYou ? `You have` : `**${member.user.username}** have`} **${memberData.calcInvites()}** invitations! (**${memberData.invites}** ordinaires, **${memberData.bonus}** bonus, **${memberData.fake > 0 ? `-${memberData.fake}` : `${memberData.fake}`}** faux, **${memberData.leaves > 0 ? `-${memberData.leaves}` : `${memberData.leaves}`}** partis)${nextRank ? `\nIl ${isYou ? `vous` : `lui`} faut encore **${nextRank.inviteCount - memberData.calcInvites()}** invitations pour obtenir le rôle **${role}** !` : ``}`,
            },
            JOINSTATS: {
                DESCRIPTION: `Displays a graph with the statistics of the members who have joined the server.`,
                USAGE: `$joinsstats`,
                EXAMPLES: `$joinsstats`,
                INVALID: `${e.error} Please specify a valid number. Between 1 and 1000`,
                TITLE: (name, numberOfDays) => `Statistics of ${name} since ${numberOfDays} days.`,
                PERCENT: (total, percent) => `${total} joined, i.e. ${percent}% of the server.`,
                RANGE: (dayRange1, dayRange2) => `Statistics from ${dayRange1} to ${dayRange2}`
            },
            SETKEEP: {
                DESCRIPTION: `Allows you to configure if members keep their roles even if they don't have enough invitations.`,
                USAGE: `$setkeep`,
                EXAMPLES: `$setkeep`,
                ENABLED: `${e.success} Keeprank is now enabled.`,
                DISABLED: `${e.success} Keeprank is now disbaled.`,
            },
            SETSTACKED: {
                DESCRIPTION: `Allows you to configure whether members accumulate their roles or not.`,
                USAGE: `$setstacked`,
                EXAMPLES: `$setstacked`,
                ENABLED: `${e.success} Stackedrank is now enabled.`,
                DISABLED: `${e.error} Stackedrank is now disabled.`,
            },
            REMOVEBONUS: {
                DESCRIPTION: `Allows you to remove bonus invitations from a user.`,
                USAGE: `$removebonus <amount> @member1 @member2 ....`,
                EXAMPLES: `$removebonus 10 @Mr¤KayJayDee @Alex`,
                NO_ARGS: `${e.error} Please specify a quantity to remove.`,
                ARGS_IS_NAN: `${e.error} Merci de vérifier la quantité spécifiée. Notez qu'elle ne peut pas être negative et ne doit pas depasser 100.`,
                IS_BOT: `${e.error} Impossible de retirer un bonus a un bot.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                SUCCESS: `${e.success} Le/les membres a/ont perdu leur bonus. Notez que les membres blacklisté ont été ignorés.`,
            },
            RESTOREINVITES: {
                DESCRIPTION: `Permet de restaurer les inviations après une reinitialisation de celles-ci.`,
                USAGE: `$restoreinvites [@membre]`,
                EXAMPLES: `$restoreinvites @Mr¤KayJayDee`,
                CONFIRM_ALL: `${e.loading} Merci de confirmer que vous êtes sûr de vouloir réinitialiser les invitations de tout les membres du serveur. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                CONFIRM_MEMBER: `${e.loading} Merci de confirmer que vous êtes sûr de vouloir réinitialiser les invitations du/des membre(s) mentionné(s). Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                CANCELLED_ALL: `${e.error} La réinitialisation des invitations de tout les membres a été annulée.`,
                CANCELLED_MEMBER: `${e.error} La réinitialisation des invitations du/des membre(s) mentionné(s) a été annulée.`,
                SUCCESS_ALL: `${e.success} Les invitations de tout les membres ont bien été réinitialisées.`,
                SUCCESS_MEMBER: `${e.success} Les invitations du/des membres mentionné(s) ont bien été réinitialisées.`,
                TIMEOUT_ALL: `${e.time} Le temp est écoulé, vous n'avez pas validé que vous vouliez réinitialiser les invitations de tout les membres du serveur.`,
                TIMEOUT_MEMBER: `${e.time} Le temp est écoulé, vous n'avez pas validé que vous vouliez réinitialiser les invitations du/des membre(s) mentionné(s).`,
            },
            SYNCINVITES: {
                DESCRIPTION: `Permet de synchroniser les invitations du serveur avec la base de donnée du bot.`,
                USAGE: `$syncinvites`,
                EXAMPLES: `$syncinvites`,
                NO_INVITES: `${e.success} Il n'y a aucune invitations a synchroniser.`,
                CONFIRM: `${e.loading} Merci de confirmer que vous êtes sûr de vouloir synchroniser les invitations de tout les membres du serveur avec la base de données. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                CANCELLED: `${e.error} La synchronisation des invitations de tout les membres a été annulée.`,
                SUCCESS: `${e.success} Les invitations de tout les membres ont bien été synchronisée.`,
                TIMEOUT: `${e.time} Le temp est écoulé, vous n'avez pas validé que vous vouliez synchroniser les invitations de tout les membres du serveur.`,
            },
            CONFIGCOMMAND: {
                DESCRIPTION: `Permet de configurer les commandes activées ou désactivées sur votre serveur.`,
                USAGE: `$configcommand <nom de la commande>`,
                EXAMPLES: `$configcommand help`,
                NO_ARGS: `${e.error} Merci de spécifier le nom d'une commande.`,
                ENABLED: `${e.success} Cette commande est maintenant activée.`,
                DISABLED: `${e.error} Cette commande est maintenant désactivée.`,
            },
            GIVEAWAY: {
                DESCRIPTION: `Permet de créer et gérer des giveaways sur vos serveurs.`,
                USAGE: `$giveaway <create/edit/end/reroll/config>`,
                EXAMPLES: `$giveaway create #giveaways-hype 10m 5 A cool role color\n$giveaway edit time <id du message de giveaway> 20m\n$giveaway reroll <id du message de giveaway>\n$giveaway end <id du message de giveaway>\n$giveaway delete <id du message de giveaway>\n$giveaway config color #FF0000 (une couleur hexadécimale)\n$giveaway config endcolor #00FF00 (une couleur hexadécimale)`,
                NO_CHANNEL: `${e.error} Merci de mentionner un canal.`,
                NO_TIME: `${e.error} Merci de spécifier un temps.`,
                TIME_IS_NAN: `${e.error} Merci de spécifier un temps valide.`,
                DAY_LIMIT: ``,
                NO_WINNERS: `${e.error} Merci de spécifier un nombre de gagnants.`,
                WINNERS_IS_NAN: `${e.error} Merci de spécifier un nombre de gagnants valide.`,
                TOO_MANY_WINNERS: `${e.error} Vous ne pouvez pas avoir plus de 50 gagnants.`,
                NO_PRIZE: `${e.error} Merci de spécifier un prix.`,
                PRIZE_TOO_LONG: `${e.error} Merci de spécifier un prix plus cours. (max 250 caractères)`,
                DELETED: `${e.success} Le giveaway a bien été suprimmé.`,
                NO_ID: `${e.error} Merci de spécifier l'id du message de giveaway.\n[Cliquez ce lien pour savoir comment l'obtenir](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)`,
                ASK_ID: `Veuillez spécifier l'ID d'un giveaway.`,
                WHAT_TO_EDIT: `Merci de choisir ce que vous voulez éditer :\n:one: : time\n:two: : prize\n:three: : winners`,
                ASK_TIME: `Veuillez spécifier combien de temp vous voulez ajouter/retirer.`,
                ASK_PRIZE: `Veuillez spécifier un nouveau prix.`,
                ASK_WINNERS: `Veuillez spécifier un nouveau nombre de gagnants.`,
                TIMEOUT_PRIZE: `${e.time} Le temp est écoulé, vous n'avez pas spécifié de nouveau prix.`,
                TIMEOUT_WINNERS: `${e.time} Le temp est écoulé, vous n'avez pas spécifié de nouveau nombre de gagnants.`,
                TIMEOUT_TIME: `${e.time} Le temp est écoulé, vous n'avez pas spécifié de temp a ajouter/retirer.`,
                TIMEOUT_REACTION: `${e.time} Le temp est écoulé, vous n'avez pas choisi d'option.`,
                TIMEOUT_ID: `${e.time} Le temp est écoulé, vous n'avezpas spécifié d'ID.\n[Cliquez ce lien pour savoir comment l'obtenir](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)`,
                CANCELLED: `${e.error} L'édition du giveaway a été annulé.`,
                UPDATE: (time) => `${e.success} Le giveaway va se mettre à jour dans moins de ${time} secondes.`,
                NO_EDIT_OPTION: `${e.error} Merci de spécifier une option a modifier: time, winner, prize`,
                END: (time) => `${e.success} Le giveaway va se terminer dans moins de ${time} secondes.`,
                NO_MESSAGE_FOUND: `${e.error} Aucun message n'a été trouvé, merci de vérifier l'ID.`,
                NO_COLOR: `${e.success} Merci de spécifier une couleur.`,
                SUCCESS_COLOR: `${e.success} La couleur des giveaways à bien été mise à jour.`,
                LINK_HEX: `${e.success} Cliquez ici pour en savoir plus.`,
                NOT_HEX: `${e.error} Merci de spécifier une couleur hexadécimale.`,
                SUCCESS_END_COLOR: `${e.success} La couleur de fin des giveaways à été mise à jour.`,
                NO_CONF_OPTION: `${e.error} Merci de spécifier une options a configurer: color, endcolor.`,
                NO_OPTION: `${e.error} Merci de spécifier une action: create, edit, reroll, end, config, delete`,
                MESSAGES: {
                    giveaway: `🎉🎉 **GIVEAWAY** 🎉🎉`,
                    giveawayEnded: `🎉🎉 **GIVEAWAY TERMINÉ** 🎉🎉`,
                    timeRemaining: `Temps restant: **{duration}**!`,
                    inviteToParticipate: `Réagissez avec 🎉 pour participer!`,
                    winMessage: `Bravo, {winners}! Vous avez gagné **{prize}**!`,
                    embedFooter: `Giveaways`,
                    noWinner: `Giveawy annulé, aucune participation valide.`,
                    hostedBy: `Par: {user}`,
                    winners: `gagnant(s)`,
                    endedAt: `Fini a`,
                    units: {
                        seconds: `secondes`,
                        minutes: `minutes`,
                        hours: `heures`,
                        days: `jours`,
                    }
                }
            },
            CLEANIFY: {
                DESCRIPTION: `Permet d'activer ou pas la supression automatique des messages du bot.`,
                USAGE: `$cleanify`,
                EXAMPLES: `$cleanify`,
                ENABLED: `${e.success} Cleanify est maintenant activé.`,
                DISABLED: `${e.error} Cleanify est maintenant désactivé.`
            },
            INVITEABOT: {
                DESCRIPTION: `Permet d'avoir un lien d'invitation en mentionnant un bot.`,
                USAGE: `$inviteabot @bot`,
                EXAMPLES: `$inviteabot @MyCoolBot`,
                NO_MENTION: `${e.error} Merci de mentionner un bot.`,
                IS_USER_MENTION: `${e.error} Vous ne pouvez pas inviter un utilisateur.`,
                SUCCESS: (name, id) => `Voici les liens pour inviter ${name} (${id})`,
            },
            CMDCHANNEL: {
                DESCRIPTION: `Permet de configurer le canal de commandes du bot.`,
                USAGE: `$commandchannel #canal`,
                EXAMPLES: `$commandchannel #commande-bot\n$commandchannel\n$commandchannel reset`,
                SUCCESS_RESET: `${e.success} Le canal de commandes à bien été retiré.`,
                SUCCES_HERE: `${e.success} Le canal de commndes sera maintenant ici.`,
                SUCCESS: `${e.success} Le canal de commandes à bien été configuré.`,
            },
            EIGHTBALL: {
                DESCRIPTION: `Permet de poser une question a la boule magique.`,
                USAGE: `$8ball <votre question>`,
                EXAMPLES: `$8ball Est-tu le meilleur des bots ?`,
                NO_ARGS: `${e.error} Merci de poser une question.`,
                NOT_A_QUESTION: `${e.error} Ceci n'est pas une question, assurez vous qu'elle se termine bien par un "?".`,
            },
            ADDBANK: {
                DESCRIPTION: `Permet d'ajouter de la monnaie dans la banque d'un utilisateur.`,
                USAGE: `$addbank <quantité> <@membre>`,
                EXAMPLES: `$addbank 100 @Mr¤KayJayDee`,
                NO_AMOUNT: `${e.error} Merci de spécifier une quantité.`,
                IS_NAN: `${e.error} Merci de vérifier la quantitée spécifiée. Notez qu'elle ne peut pas être negative et ne doit pas depasser 10 000.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IS_BOT: `${e.error} Impossible d'ajouter de la monnaie sur le compte en banque d'un bot.`,
                TITLE: (username) => `Ajout de monnaie dans la banque de ${username}.`,
                RESULT: (startSolde, toAdd, newSolde) => `Cet utilisateur avait ${startSolde}€, vous venez de lui ajouter ${toAdd}€, il possède maintenant ${newSolde}€ dans son compte en banque.`,
            },
            ADDMONEY: {
                DESCRIPTION: `Permet d'ajouter de la monnaie a un utilisateur.`,
                USAGE: `$addmoney <quantité> <@membre>`,
                EXAMPLES: `$addmoney 100 @Mr¤KayJayDee`,
                NO_AMOUNT: `${e.error} Merci de spécifier une quantité.`,
                IS_NAN: `${e.error} Merci de vérifier la quantitée spécifiée. Notez qu'elle ne peut pas être negative et ne doit pas depasser 10 000.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IS_BOT: `${e.error} Impossible d'ajouter de la monnaie a un bot.`,
                TITLE: (username) => `Ajout de monnaie dans le porte monnaie de ${username}.`,
                RESULT: (startSolde, toAdd, newSolde) => `Cet utilisateur avait ${startSolde}€, vous venez de lui ajouter ${toAdd}€, il possède maintenant ${newSolde}€ dans son porte monnaie.`,
            },
            VERIFGUILDBL: {
                DESCRIPTION: `Permet de vérifier si il y a des utilisateurs blacklistés sur le serveur.`,
                USAGE: `$verifguildbl`,
                EXAMPLES: `$verifguildbl`,
                NO_USER: `${e.success} Il n'y a aucun utilisateur blacklisté sur le serveur.`,
                LIST: `Voici la liste des utilisateurs blacklistés.`,
            },
            BALANCE: {
                DESCRIPTION: `Permet de voir la quantité de monnaie que vous avez dans votre porte-monnaie.`,
                USAGE: `$balance`,
                EXAMPLES: `$balance`,
                TITLE: (username) => `Porte monnaie de ${username}`,
                INFOS: (amount) => `Vous avez actuellement ${amount} € en dans votre porte-monnaie.`,
            },
            BANK: {
                DESCRIPTION: `Permet de voir la quantité de monnaie que vous avez dans votre compte en banque.`,
                USAGE: `$bank`,
                EXAMPLES: `$bank`,
                TITLE: (username) => `Compte en banque de ${username}`,
                INFOS: (amount) => `Vous avez actuellement ${amount} € en dans votre compte en banque.`,
            },
            DAILY: {
                DESCRIPTION: `Permet de récupérer une récompense toute les 24h.`,
                USAGE: `$daily`,
                EXAMPLES: `$daily`,
                TITLE: (username) => `Récompense journalière de ${username}`,
                TIME: (hours, minutes, seconds) => `${e.time} Merci de patienter encore ${hours}h ${minutes}m ${seconds}s avant de pouvoir récupérer votre prochaine récompense.`,
                DAILY: (collected) => `Vous venez de récolter ${collected}€.`,
            },
            WEEKLY: {
                DESCRIPTION: `Permet de récupérer une récompense tout les 7j.`,
                USAGE: `$weekly`,
                EXAMPLES: `$weekly`,
                TITLE: (username) => `Récompense hebdomadaire de ${username}`,
                TIME: (days, hours, minutes, seconds) => `${e.time} Merci de patienter encore ${days}j ${hours}h ${minutes}m ${seconds}s avant de pouvoir récupérer votre prochaine récompense.`,
                WEEKLY: (collected) => `Vous venez de récolter ${collected}€.`,
            },
            MONTHLY: {
                DESCRIPTION: `Permet de récupérer une récompense tout les 30jours.`,
                USAGE: `$monthly`,
                EXAMPLES: `$monthly`,
                TITLE: (username) => `Récompense mensuelle de ${username}`,
                TIME: (days, hours, minutes, seconds) => `${e.time} Merci de patienter encore ${days}j ${hours}h ${minutes}m ${seconds}s avant de pouvoir récupérer votre prochaine récompense.`,
                MONTHLY: (collected) => `Vous venez de récolter ${collected}€.`,
            },
            WORK: {
                DESCRIPTION: `Permet de récupérer une récompense toutes les 6h.`,
                USAGE: `$work`,
                EXAMPLES: `$work`,
                TITLE: (username) => `Récompense de travail de ${username}`,
                TIME: (hours, minutes, seconds) => `${e.time} Merci de patienter encore ${hours}h ${minutes}m ${seconds}s avant de pouvoir récupérer votre prochaine récompense.`,
                WORK: (collected) => `Vous venez de récolter ${collected}€.`,
            },
            ROB: {
                DESCRIPTION: `Permet de voler un autre membre tout les 12h.`,
                USAGE: `$rob <@membre>`,
                EXAMPLES: `$rob @Mr¤KayJayDee`,
                TITLE: (username) => `${username} viens de voler un autre membre.`,
                TIME: (hours, minutes, seconds) => `${e.time} Merci de patienter encore ${hours}h ${minutes}m ${seconds}s avant de pouvoir voler quelqu'un d'autre.`,
                ROB: (collected) => `Vous venez de voler ${collected}€.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                INVALID: `${e.error} Vous ne pouvez pas voler un bot ni vous-même.`,
                NOTHING_TO_ROB: `${e.error} Ce membre n'a rien à voler.`,
                NEED_MIN: `${e.error} Vous devez avoir minimum 250€ dans votre porte-monnaie pour pouvoir voler quelqu'un.`,
                FAIL: (amount) => `${e.error} Vous avez raté votre vol et perdez ${amount}€`,
            },
            DEPOSIT: {
                DESCRIPTION: `Permet de déposer de l'argent sur votre compte en banque.`,
                USAGE: `$deposit <quantité>`,
                EXAMPLES: `$deposit 100\n$deposit all`,
                NO_ARGS: `${e.error} Merci de spécifier une quantité.`,
                IS_NAN: `${e.error} Merci de vérifier la quantitée spécifiée. Notez qu'elle ne peut pas être negative.`,
                NOT_ENOUGH: `${e.error} Vous n'avez pas cette somme dans votre porte-monnaie, impossible de déposer sur votre compte en banque.`,
                DEP_AMOUNT: (isAll, amount) => `Vous venez de deposer ${isAll ? ` tout votre argent ` : `${amount}€`} sur votre compte en banque.`,
            },
            WITHDRAW: {
                DESCRIPTION: `Permet de retirer de l'argent sur votre porte-monnaie.`,
                USAGE: `$withdraw <quantité>`,
                EXAMPLES: `$withdraw 100\n$withdraw all`,
                NO_ARGS: `${e.error} Merci de spécifier une quantité.`,
                IS_NAN: `${e.error} Merci de vérifier la quantitée spécifiée. Notez qu'elle ne peut pas être negative.`,
                NOT_ENOUGH: `${e.error} Vous n'avez pas cette somme sur votre compte en banque, impossible de retirer dans votre porte-monnaie.`,
                WD_AMOUNT: (isAll, amount) => `Vous venez de retirer ${isAll ? ` tout votre argent ` : `${amount}€`} sur votre porte-monnaie.`,
            },
            REPUTATION: {
                DESCRIPTION: `Permet de donner un point de réputation à un autre membre.`,
                USAGE: `$reputation`,
                EXAMPLES: `$reputation`,
                TITLE: (username) => `${username} viens de donner un point de réputation.`,
                TIME: (minutes, seconds) => `${e.time} Merci de patienter encore ${minutes}m ${seconds}s avant de donner un point de réputation a quelqu'un d'autre.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                INVALID: `${e.error} Vous ne pouvez pas donner de points de réputation un bot ni vous-même.`,
                REP: (name) => `Vous venez de donner un point de réputation a ${name}`,
            },
            PAY: {
                DESCRIPTION: `Permet de payer un utilisateur.`,
                USAGE: `$pay <quantité> <@membre>`,
                EXAMPLES: `$pay 100 @Mr¤KayJayDee`,
                NO_AMOUNT: `${e.error} Merci de spécifier une quantité.`,
                IS_NAN: `${e.error} Merci de vérifier la quantitée spécifiée. Notez qu'elle ne peut pas être negative et ne doit pas depasser 10 000.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IS_BOT: `${e.error} Impossible de payer un bot.`,
                NOT_ENOUGH: `${e.error} Vous n'avez pas cette quantitée dans votre porte-monnaie, payment impossible.`,
                TITLE: (username) => `Payment pour ${username}.`,
                RESULT: (startSolde, toAdd, newSolde) => `Cet utilisateur avait ${startSolde}€, vous venez de lui payer ${toAdd}€, il possède maintenant ${newSolde}€ dans son porte-monnaie.`,
            },
            REMOVEBANK: {
                DESCRIPTION: `Permet de suprimmer de la monnaie dans la banque d'un utilisateur.`,
                USAGE: `$removebank <quantité> <@membre>`,
                EXAMPLES: `$removebank 100 @Mr¤KayJayDee`,
                NO_AMOUNT: `${e.error} Merci de spécifier une quantité.`,
                IS_NAN: `${e.error} Merci de vérifier la quantitée spécifiée. Notez qu'elle ne peut pas être negative et ne doit pas depasser 10 000.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IS_BOT: `${e.error} Impossible de suprimmer de la monnaie sur le compte en banque d'un bot.`,
                NEGATIVE: `${e.success} La valeur que vous avez entré était trop haute par rapport a la quantitée que possède cet utilisateur, sa banque a donc été remise a 0.`,
                TITLE: (username) => `Supression de monnaie dans la banque de ${username}.`,
                RESULT: (startSolde, toAdd, newSolde) => `Cet utilisateur avait ${startSolde}€, vous venez de lui suprimmer ${toAdd}€, il possède maintenant ${newSolde}€ dans son compte en banque.`,
            },
            REMOVEMONEY: {
                DESCRIPTION: `Permet de suprimmer de la monnaie a un utilisateur.`,
                USAGE: `$removemoney <quantité> <@membre>`,
                EXAMPLES: `$removemoney 100 @Mr¤KayJayDee`,
                NO_AMOUNT: `${e.error} Merci de spécifier une quantité.`,
                IS_NAN: `${e.error} Merci de vérifier la quantitée spécifiée. Notez qu'elle ne peut pas être negative et ne doit pas depasser 10 000.`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IS_BOT: `${e.error} Impossible de suprimmer de la monnaie a un bot.`,
                NEGATIVE: `${e.success} La valeur que vous avez entré était trop haute par rapport a la quantitée que possède cet utilisateur, son porte-monnaie a donc été remis a 0.`,
                TITLE: (username) => `Supression de monnaie dans le porte monnaie de ${username}.`,
                RESULT: (startSolde, toAdd, newSolde) => `Cet utilisateur avait ${startSolde}€, vous venez de lui suprimmer ${toAdd}€, il possède maintenant ${newSolde}€ dans son porte monnaie.`,
            },
            SEEBALANCE: {
                DESCRIPTION: `Permet de voir la quantité de monnaie qu'un utilisateur à dans son porte-monnaie.`,
                USAGE: `$seebalance <@membre>`,
                EXAMPLES: `$seebalance @Mr¤KayJayDee`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IS_BOT: `${e.error} Impossible de voir le porte-monnaie d'un bot.`,
                TITLE: (username) => `Porte monnaie de ${username}`,
                INFOS: (amount) => `Cet utilisateur a actuellement ${amount} € en dans son porte-monnaie.`,
            },
            SEEBANK: {
                DESCRIPTION: `Permet de voir la quantité de monnaie qu'un utilisateur à sur son compte en banque.`,
                USAGE: `$seebank <@membre>`,
                EXAMPLES: `$seebank @Mr¤KayJayDee`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IS_BOT: `${e.error} Impossible de voir la banque d'un bot.`,
                TITLE: (username) => `Banque de ${username}`,
                INFOS: (amount) => `Cet utilisateur a actuellement ${amount} € en sur son compte en banque.`,
            },
            SETBIO: {
                DESCRIPTION: `Permet de configurer votre biographie.`,
                USAGE: `$setbio <votre biographie>`,
                EXAMPLES: `$setbio Salut, je suis Amandine, je suis le meilleur des bots. 😉`,
                NO_TEXT: `${e.error} Merci de spécifier un texte de biographie.`,
                TOO_LONG: `${e.error} Votre biographie ne doit pas dépasser les 1000 caractères.`,
                TITLE: (username) => `Biographie de ${username}`,
                NEWBIO: (newbio) => `Votre nouvelle biographie à bien été enregistrée :\n\`\`\`${newbio}\`\`\``,
            },
            SETSEX: {
                DESCRIPTION: `Permet de configurer la langue du bot.`,
                USAGE: `$setsex <sexe>`,
                EXAMPLES: `$setsex homme\n$setsex femme`,
                NO_ARGS: (sexs) => `${e.error} Merci de spécifier un sexe. Voici ceux disponibles: ${sexs}`,
                INVALID_SEX: (sexs) => `${e.error} Merci de spécifier un sexe valide. Voici celles disponibles: ${sexs}`,
                SUCCESS: (sex) => `${e.success} Votre sexe est mainenant configuré sur: ${sex}`,
            },
            PROFILE: {
                DESCRIPTION: `Permet de voir votre profil ou celui d'un membre.`,
                USAGE: `$profile [@membre]`,
                EXAMPLES: `$profile\n$profile @Mr¤KayJayDee`,
                TITLE: (username) => `Profil de ${username}`,
                BIO: (bio) => `${e.desc2} **Biographie:** \n> ${bio}`,
                SEX: (sex) => `${e.gender} **Sexe:** ${sex}`,
                REP: (points) => `${e.reputation} **Points de réputation:** ${points}`,
            },
            ASCII: {
                DESCRIPTION: `Permet d'asciifier un texte.`,
                USAGE: `$ascii <message>`,
                EXAMPLES: `$ascii Amandine`,
                NO_ARGS: `${e.error} Merci de spécifier un message.`,
                LIMIT: `${e.error} Merci de spécifier un message de moins de 14 caractères.`,
            },
            AVATAR: {
                DESCRIPTION: `Permet de voir votre photo de profil ou celle de vos amis.`,
                USAGE: `$avatar [@membre]`,
                EXAMPLES: `$avatar\n$avatar @Mr¤KayJayDee`,
            },
            B64: {
                DESCRIPTION: `Permet d'encoder ou décoder un message en Base 64.`,
                USAGE: `$b64 <encode/decode> <message> `,
                EXAMPLES: `$b64 encode Amandine\n$b64 decode QW1hbmRpbmU=`,
                NO_ARGS: `${e.error} Merci de spécifier une action: encode, decode.`,
                NO_ARGS_E: `${e.error} Merci de spécifier un message a encoder.`,
                NO_ARGS_D: `${e.error} Merci de spécifier un message a décoder.`,
            },
            BAN: {
                DESCRIPTION: `Permet de bannir un membre.`,
                USAGE: `$ban <@membre> [raison]`,
                EXAMPLES: `$ban @Mr¤KayJayDee\n$ban @Mr¤KayJayDee Trop bon dev`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IMPOSSIBLE_BAN: `${e.error} Impossible de bannir cet utilisateur.`,
                NO_REASON: `Aucune raison donnée`,
                MEMBER_RESULT: (guild, author, reason) => `Vous venez d'être banni par ${author} sur le serveur ${guild} (Raison: ${reason}).`,
                GUILD_RESULT: (reason) => `Cet utilisateur a bien été banni du serveur (Raison: ${reason}).`,
            },
            KICK: {
                DESCRIPTION: `Permet d'expulser un membre.`,
                USAGE: `$kick <@membre> [raison]`,
                EXAMPLES: `$kick @Mr¤KayJayDee\n$kick @Mr¤KayJayDee Trop bon dev`,
                NO_MENTION: `${e.error} Please mention a member.`,
                IMPOSSIBLE_KICK: `${e.error} Impossible d'expluser cet utilisateur.`,
                NO_REASON: `Aucune raison donnée`,
                MEMBER_RESULT: (guild, author, reason) => `Vous venez d'être expulsé par ${author} sur le serveur ${guild} (Raison: ${reason}).`,
                GUILD_RESULT: (reason) => `Cet utilisateur a bien été expulsé du serveur (Raison: ${reason}).`,
            },
            BIGTEXT: {
                DESCRIPTION: `Permet de grossir votre texte en emojis.`,
                USAGE: `$bigtext <message>`,
                EXAMPLES: `$bigtext Salut, je suis Amandine, je suis le meilleur des bots.`,
                NO_ARGS: `${e.error} Merci de spécifier un message.`,
                LIMIT: `${e.error} Merci de spécifier un message de moins de 14 caractères.`,
            },
            ANIMAL: {
                DESCRIPTION: `Affiche une photo d'animal.`,
                USAGE: `$animal`,
                EXAMPLES: `$animal`,
            },
            CAR: {
                DESCRIPTION: `Affiche une photo de voiture.`,
                USAGE: `$car`,
                EXAMPLES: `$car`,
            },
            CAT: {
                DESCRIPTION: `Affiche une photo de chat.`,
                USAGE: `$cat`,
                EXAMPLES: `$cat`,
            },
            COMICS: {
                DESCRIPTION: `Affiche une photo de comics.`,
                USAGE: `$comics`,
                EXAMPLES: `$comics`,
            },
            COSPLAY: {
                DESCRIPTION: `Affiche une photo de cosplay.`,
                USAGE: `$cosplay`,
                EXAMPLES: `$cosplay`,
            },
            DOG: {
                DESCRIPTION: `Affiche une photo de chien.`,
                USAGE: `$dog`,
                EXAMPLES: `$dog`,
            },
            DRAGONBALL: {
                DESCRIPTION: `Affiche une photo de dragon ball.`,
                USAGE: `$dragonball`,
                EXAMPLES: `$dragonball`,
            },
            EMMAWATSON: {
                DESCRIPTION: `Affiche une photo d'Emma Watson.`,
                USAGE: `$emmawatson`,
                EXAMPLES: `$emmawatson`,
            },
            FOOD: {
                DESCRIPTION: `Affiche une photo de nourriture.`,
                USAGE: `$food`,
                EXAMPLES: `$food`,
            },
            GIRL: {
                DESCRIPTION: `Affiche une photo de fille.`,
                USAGE: `$girl`,
                EXAMPLES: `$girl`,
            },
            MANGA: {
                DESCRIPTION: `Affiche une photo de manga.`,
                USAGE: `$manga`,
                EXAMPLES: `$manga`,
            },
            NATURE: {
                DESCRIPTION: `Affiche une photo de la nature.`,
                USAGE: `$nature`,
                EXAMPLES: `$nature`,
            },
            SPACEPIC: {
                DESCRIPTION: `Affiche une photo de l'espace.`,
                USAGE: `$spacepic`,
                EXAMPLES: `$spacepic`,
            },
            VANGOGH: {
                DESCRIPTION: `Affiche un tableau de Vangogh.`,
                USAGE: `$vangogh`,
                EXAMPLES: `$vangogh`,
            },
            WALLPAPER: {
                DESCRIPTION: `Affiche un fond d'écran.`,
                USAGE: `$wallpaper`,
                EXAMPLES: `$wallpaper`,
            },
            BLUR: {
                DESCRIPTION: `Applique l'effet flou a votre photo de profil ou celle de vos amis.`,
                USAGE: `$blur`,
                EXAMPLES: `$blur`,
            },
            URBAN: {
                DESCRIPTION: `Affiche une photo urban.`,
                USAGE: `$urban`,
                EXAMPLES: `$urban`,
            },
            GAY: {
                DESCRIPTION: `Applique le filtre gay a votre photo de profil ou celle de vos amis.`,
                USAGE: `$gay`,
                EXAMPLES: `$gay`,
            },
            GREYSCALE: {
                DESCRIPTION: `Applique le filtre noir et blanc a votre photo de profil ou celle de vos amis.`,
                USAGE: `$greyscale`,
                EXAMPLES: `$greyscale`,
            },
            INVERT: {
                DESCRIPTION: `Applique l'effet inverse a votre photo de profil ou celle de vos amis.`,
                USAGE: `$invert`,
                EXAMPLES: `$invert`,
            },
            SEPIA: {
                DESCRIPTION: `Applique le filtre sépia a votre photo de profil ou celle de vos amis.`,
                USAGE: `$sepia`,
                EXAMPLES: `$sepia`,
            },
            CIRCLE: {
                DESCRIPTION: `Transforme votre photo de profil ou celle de vos amis en un cercle.`,
                USAGE: `$circle`,
                EXAMPLES: `$circle`,
            },
            BAKA: {
                DESCRIPTION: `Permet de baka un membre.`,
                USAGE: `$baka <@membre>`,
                EXAMPLES: `$baka @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de baka **${user}**`,
            },
            CUDDLE: {
                DESCRIPTION: `Permet de faire des papouilles membre.`,
                USAGE: `$cuddle <@membre>`,
                EXAMPLES: `$cuddle @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de faire des papouilles a **${user}**`,
            },
            FEED: {
                DESCRIPTION: `Permet de nourrir membre.`,
                USAGE: `$feed <@membre>`,
                EXAMPLES: `$feed @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de nourrire **${user}**`,
            },
            HUG: {
                DESCRIPTION: `Permet de faire un câlin à un membre.`,
                USAGE: `$hug <@membre>`,
                EXAMPLES: `$hug @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de faire un câlin a **${user}**`,
            },
            KILL: {
                DESCRIPTION: `Permet de tuer un membre.`,
                USAGE: `$kill <@membre>`,
                EXAMPLES: `$kill @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de tuer **${user}**`,
            },
            KISSGIF: {
                DESCRIPTION: `Permet de faire un bisous (gif) a un membre.`,
                USAGE: `$kissgif <@membre>`,
                EXAMPLES: `$kissgif @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de faire un bisous a **${user}**`,
            },
            PAT: {
                DESCRIPTION: `Permet de tapoter un membre.`,
                USAGE: `$pat <@membre>`,
                EXAMPLES: `$pat @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de tapoter **${user}**`,
            },
            POKE: {
                DESCRIPTION: `Permet de toucher un membre.`,
                USAGE: `$poke <@membre>`,
                EXAMPLES: `$poke @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de toucher **${user}**`,
            },
            SLAP: {
                DESCRIPTION: `Permet de mettre une claque à un membre.`,
                USAGE: `$slap <@membre>`,
                EXAMPLES: `$slap @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de mettre une claque à **${user}**`,
            },
            TICKLE: {
                DESCRIPTION: `Permet de chatouiller un membre.`,
                USAGE: `$tickle <@membre>`,
                EXAMPLES: `$tickle @Mr¤KayJayDee`,
                MESSAGE: (author, user) => `**${author}** vient de chatouiller **${user}**`,
            },
            TRIGGERED: {
                DESCRIPTION: `Permet de générer une image triggered avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$triggered <@membre>`,
                EXAMPLES: `$triggered @Mr¤KayJayDee`,
            },
            AD: {
                DESCRIPTION: `Permet de générer une image ad avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$ad <@membre>`,
                EXAMPLES: `$ad @Mr¤KayJayDee`,
            },
            AFFECT: {
                DESCRIPTION: `Permet de générer une image affect avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$affect <@membre>`,
                EXAMPLES: `$affect @Mr¤KayJayDee`,
            },
            BATSLAP: {
                DESCRIPTION: `Permet de générer une image batslap avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$batslap <@membre>`,
                EXAMPLES: `$batslap @Mr¤KayJayDee`,
            },
            BEAUTIFUL: {
                DESCRIPTION: `Permet de générer une image beautiful avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$beautiful <@membre>`,
                EXAMPLES: `$beautiful @Mr¤KayJayDee`,
            },
            BED: {
                DESCRIPTION: `Permet de générer une image bed avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$bed <@membre>`,
                EXAMPLES: `$bed @Mr¤KayJayDee`,
            },
            CONFUSEDSTONK: {
                DESCRIPTION: `Permet de générer une image confusedstonk avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$confusedstonk <@membre>`,
                EXAMPLES: `$confusedstonk @Mr¤KayJayDee`,
            },
            DELETE: {
                DESCRIPTION: `Permet de générer une image delete avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$delete <@membre>`,
                EXAMPLES: `$delete @Mr¤KayJayDee`,
            },
            FACEPALM: {
                DESCRIPTION: `Permet de générer une image facepalm avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$facepalm <@membre>`,
                EXAMPLES: `$facepalm @Mr¤KayJayDee`,
            },
            HITLER: {
                DESCRIPTION: `Permet de générer une image hitler avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$hitler <@membre>`,
                EXAMPLES: `$hitler @Mr¤KayJayDee`,
            },
            JAIL: {
                DESCRIPTION: `Permet de générer une image jail avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$jail <@membre>`,
                EXAMPLES: `$jail @Mr¤KayJayDee`,
            },
            KISS: {
                DESCRIPTION: `Permet de générer une image kiss avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$kiss <@membre>`,
                EXAMPLES: `$kiss @Mr¤KayJayDee`,
            },
            LISAPRESENTATION: {
                DESCRIPTION: `Permet de générer une image lisapresentation avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$lisapresentation <votre message>`,
                EXAMPLES: `$lisapresentation Salut, je suis Amandine, je suis le meilleur des bots.`,
            },
            MMS: {
                DESCRIPTION: `Permet de générer une image mms avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$mms <@membre>`,
                EXAMPLES: `$mms @Mr¤KayJayDee`,
            },
            NOTSTONK: {
                DESCRIPTION: `Permet de générer une image notstonk avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$notstonk <@membre>`,
                EXAMPLES: `$notstonk @Mr¤KayJayDee`,
            },
            PODIUM: {
                DESCRIPTION: `Permet de générer une image triggered avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$triggered <@membre> <@membre>`,
                EXAMPLES: `$triggered @Mr¤KayJayDee @Alex`,
            },
            PUTIN: {
                DESCRIPTION: `Permet de générer une image putin avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$putin <@membre>`,
                EXAMPLES: `$putin @Mr¤KayJayDee`,
            },
            RIP: {
                DESCRIPTION: `Permet de générer une image rip avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$rip <@membre>`,
                EXAMPLES: `$rip @Mr¤KayJayDee`,
            },
            SPANK: {
                DESCRIPTION: `Permet de générer une image spank avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$spank <@membre>`,
                EXAMPLES: `$spank @Mr¤KayJayDee`,
            },
            STONK: {
                DESCRIPTION: `Permet de générer une image stonk avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$stonk <@membre>`,
                EXAMPLES: `$stonk @Mr¤KayJayDee`,
            },
            TATOO: {
                DESCRIPTION: `Permet de générer une image tatoo avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$tatoo <@membre>`,
                EXAMPLES: `$tatoo @Mr¤KayJayDee`,
            },
            THOMAS: {
                DESCRIPTION: `Permet de générer une image thomas avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$thomas <@membre>`,
                EXAMPLES: `$thomas @Mr¤KayJayDee`,
            },
            WANTED: {
                DESCRIPTION: `Permet de générer une image wanted avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$wanted <@membre>`,
                EXAMPLES: `$wanted @Mr¤KayJayDee`,
            },
            TRASH: {
                DESCRIPTION: `Permet de générer une image trash avec votre photo de profil ou celle de vos amis.`,
                USAGE: `$trash <@membre>`,
                EXAMPLES: `$trash @Mr¤KayJayDee`,
            },
            BLINK: {
                DESCRIPTION: `Permet de générer une image clignotement avec votre photo de profil et celle de vos amis.`,
                USAGE: `$blink <@membre>  [délais (en ms)]`,
                EXAMPLES: `$blink @Mr¤KayJayDee 2000`,
                NO_MENTION: `${e.error} Please mention a member.`,
                INVALID: `${e.error} Vous ne pouvez pas appliquer cet effet a vous-même.`,
                IS_NAN: `${e.error} Merci de spécifier un nombre valide. (en ms)`,
            },
            HANGMAN: {
                DESCRIPTION: `Permet de jouer au pendu tout seul ou entre amis.`,
                USAGE: `$hangman <mode de jeu(random/custom)>`,
                EXAMPLES: `$hangman random\n$hangman custom`,
                TITLE: `Tutoriel pour le pendu`,
                START_TITLE: `Démarrer une partie`,
                START: (prefix) => `\`${prefix}hangman [custom | random]\`. Custom par défaut. Custom veut dire qu'un des joueurs va devoir choisir le mot. En Random, le mot sera choisi au hasard par le bot. (Vous pouvez suggérer des mot à ajouter en rejoignant le [serveur de support](https://discord.gg/Uqd2sQP))`,
                JOIN_TITLE: `Rejoindre la partie`,
                JOIN: `Réagissez avec "📒" ou entrer "join" dans le chat quand vous voyez un message qui vous le demande..`,
                PLAY_TITLE: `Jouer`,
                PLAY: `Quand la partie a démmaré et qu'un pendu apparait a l'écran, vous devez trouver le mot. Si vous envoyez une lettre, vous demandez si la lettre est dans le mot. Si vous envoyer plus d'une lettre (un mot) vous demandez si vous avez le bon mot, dans le cas ou vous vous trompez, vous êtes éliminé de la partie.`,
                ASK_PLAYERS: `Écrivez "join" dans le chat ou réagissez avec "📒" pour entrer dans la partie, vous avez 10 secondes.`,
                ASK_WORD_DM: `Hey ! Tu à été séléctionné pour choisir le mot de cette partie Tu as 30 secondes. Rappelle toi que tu ne peut pas jouer durant cette partie.`,
                DM_TIMEOUT: `${e.error} Vous n'avez pas choisi de mot pour la partie dans les temps, vous avez donc été élimininé.`,
                DM_TIMEOUT_CHANNEL: `${e.error} L'utilisateur séléctionné n'a pas repondu a mon message pour choisir un mot veuillez rééxecuter la commande.`,
                WORD_SUCCESS: `${e.success} Joli mot, vous pouvez maintenant retourner sur le serveur.`,
                INVALID_WORD: `${e.error} Ce n'est pas un mot valide, il doit être plus long que 3 lettres et ne doit pas contenir d'espaces`,
                RAN_OUT_PLAYERS: `${e.error} Il n'y a plus assez de joueurs dans la partie, veuillez rééssayer.`,
                MISSES: `Loupé: `,
                WON: `Vous avez gagné`,
                LOST: `Vous avez perdu`,
                NO_ONE_JOINED: `${e.error} Personne n'a rejoint la partie, veuillez rééssayer.`,
                NO_ONE_JOINED_CUSTOM: `${e.error} Personne n'a rejoint la partie, il faut minimum deux utilisateurs pour une partie personalisée, veuillez rééssayer.`,
                WAIT_WORD: (players) => `${e.time} ${players} utilisateurs ont rejoints. Selection d'un joueur pour choisir le mot. En attente d'un réponse. Allez voir vos messages privés !`,
                RESULT_WON_CUSTOM: (name) => `${e.success} Bravo vous avez trouvé le mot de ${name}, la prochaine fois il vous en donneras un plus compliqué.`,
                RESULT_WON: `${e.success} Vous avez gagné cette fois mais la prochaine fois cela ne sera pas le cas.`,
                RESULT_LOST_CUSTOM: (name, word) => `${e.error} Désolé vous avez perdu contre **${name}**, le mot était **${word}**.`,
                RESULT_LOST: (word) => `${e.error} Désolé vous avez perdu, le mot était **${word}**.`,
                TIMEOUT: `${e.time} La partie s'est terminée automatiquement du a une inactivité de 5 minutes.`,
                ALREADY_RUNNING: `${e.error} Il y à déja une partie en cours dans ce canal, veuillez vous rendre dans un autre.`,
            },
            BANLIST: {
                DESCRIPTION: `Permet de voir la liste des utilisateurs bannis du serveur.`,
                USAGE: `$banlist`,
                EXAMPLES: `$banlist`,
                NO_BAN: `${e.error} Il n'y a aucun utilisateur bannis sur le serveur.`,
                TITLE: `Voici la liste des utilisateurs bannis`,
            },
            CHANNELINFO: {
                DESCRIPTION: `Permet de voir les informations d'un canal.`,
                USAGE: `$channelinfo [#canal/ID]`,
                EXAMPLES: `$channelinfo #général-chat\n$channelinfo 123456789`,
                INFOS: (channel, id, date, topic, position, nsfw) => `**Informations sur le canal:** ${channel}\n\n🆔 | ID: **${id}**\n🕐 | Date de création: **${date}**\n📕 | Sujet: **${topic}**\n🔢 | Position: **${position}**\n🔞 | NSFW: **${nsfw}**`,
            },
            ROLEINFO: {
                DESCRIPTION: `Permet de voir les informations d'un rôle.`,
                USAGE: `$roleinfo [@role/ID]`,
                EXAMPLES: `$roleinfo @amis\n$roleinfo 123456789`,
                INFOS: (role, members, color, id, mention, position, managed, displayed, date) => `**Informations sur le role:** ${role}\n\n🔢 | Nombre de membres ayant ce rôle: **${members}**\n#️⃣ | Couleur hexadécimale: **${color}**\n🆔 | ID: **${id}**\n🌐 | Mentionnable: **${mention}**\n1️⃣ | Position: **${position}**\n🤖 | Géré par un bot: **${managed}**\n👀 | Affiché séparément: **${displayed}**\n🕐 | Date de création: **${date}**`,
            },
            SERVERINFO: {
                DESCRIPTION: `Permet de voir les informations du serveur.`,
                USAGE: `$serverinfo`,
                EXAMPLES: `$serverinfo`,
                INFOS: (owner, name, date, members, humans, bots, channels, roles, emojis, online, dnd, idle, offline, streaming, region, verification) => `**${name} - Informations**\n\n👑 | Propriétaire du serveur: **${owner}**\n🔤 | Nom du serveur: **${name}**\n🕐 | Date de création: **${date}**\n🌍 | Région du serveur: **${region}**\n🛂 | Niveau de vérification: **${verification}**\n🔢 | Nombre de membres: **${members}**\n👨 | Humains: **${humans}**\n🤖 | Bots: **${bots}**\n🔋 | Status des membres: \n\t> ${e.status.online} **${online}** membres en ligne\n> ${e.status.dnd} **${dnd}** membres en ne pas déranger\n> ${e.status.idle} **${idle}** membres inactifs\n> ${e.status.streaming} **${streaming}** membres en streaming\n> ${e.status.offline} **${offline}** membres hors ligne\n📌 | Nombre de salon: **${channels}**\n📕 | Nombre de rôles: **${roles}**\n💯 | Nombre d'émojis: **${emojis}**`,
            },
            MEMBERINFO: {
                DESCRIPTION: `Permet de voir les informations d'un membre.`,
                USAGE: `$memberinfo <@membre/ID>`,
                EXAMPLES: `$memberinfo @Mr¤KayJayDee\n$memberinfo 123456789`,
                INFOS: (member, type, joinedAt, createdAt, kickable, bannable, joinPosition, joinOrder, badges) => `**Informations sur le membre:** ${member}\n\n🔤 | Nom: **${member.user.username}**\n#️⃣ | Discriminant: **#${member.user.discriminator}**\n🆔 | ID: **${member.user.id}**\n📛 | Badges: ${badges}\n🏹 | Type: **${type}**\n🚪 | Arrivée sur le serveur: **${joinedAt}**\n🛠️ | Date de création du compte: **${createdAt}**\n⚙️ | Kickable: **${kickable}**\n⚙️ | Bannissable: **${bannable}**\n🔢 | Position d'arrivée: **${joinPosition}**\n🔁 | Ordre d'arrivée: ${joinOrder}`,
                BOT: `🤖 Bot`,
                HUMAN: `👨 Humain`,
            },
            DICE: {
                DESCRIPTION: `Permet de tirer un dé.`,
                USAGE: `$dice <nombre minimum> <nombre maximum>`,
                EXAMPLES: `$dice 1 6\n$dice 100 200`,
                INVALID: `${e.error} Merci de spécifier deux nombres valides, le premier étant le plus petit.`,
                RESULT: (number) => `${e.success} Le dé est tombé sur ${number}.`,
            },
            DONATE: {
                DESCRIPTION: `Permet de voir les informations sur comment soutenir le projet.`,
                USAGE: `$donate`,
                EXAMPLES: `$donate`,
                TITLE: `Voici comment vous pouvez soutenir le projet.`,
                INFOS: `Vous pouvez me "payer un café" en cliquant sur ce lien [BuyMeACoffee.com](https://www.buymeacoffee.com/amandine).\nVous pouvez aussi envoyer la quantitée PayPal que vous voulez a cette adresse \`killian.dalcin@gmail.com\`. Rien n'est obligé libre a vous de m'aider ou pas. :wink:`,
            },
            VOTE: {
                DESCRIPTION: `Permet de voir les sites ou vous povez voter pour le bot.`,
                USAGE: `$vote`,
                EXAMPLES: `$vote`,
                TITLE: `Voici comment vous pouvez voter pour le bot.`,
                INFOS: `Si vous aimez mon bot vous pouvez me soutenir en suivant ces liens et en votant pour le bot: [TOP.GG](https://top.gg/bot/534074921488351234/vote), [Discord Boats](https://discord.boats/bot/534074921488351234/vote), [Discord bot list](https://discordbotlist.com/bots/amandine/upvote), [Arcane](https://arcane-center.xyz/bot/534074921488351234), [Wonder Bot List](https://wonderbotlist.com/en/bot/534074921488351234/vote), [Bots Database](https://botsdatabase.com/bot/534074921488351234)`,
            },
            ADDROLE: {
                DESCRIPTION: `Permet d'ajouter un rôle a un membre'.`,
                USAGE: `$addrole <@membre/ID> <@role/ID>`,
                EXAMPLES: `$addrole @Mr¤KayJayDee @amis\n$addrole @Mr¤KayJayDee 123456789`,
                NO_MEMBER: `${e.error} Please mention a member.`,
                NO_ROLE: `${e.error} Merci de mentionner un rôle.`,
                INVALID: `${e.error} Merci de spécifier un rôle valide et de vérifier que mon plus haut rôle est au dessus du rôle que vous voulez ajouter et au dessus du plus haut rôle du membre a qui vous voulez l'ajouter.`,
                ALREADY_HAS_ROLE: (member, role) => `${e.success} **${member}** à déjà le rôle **${role}**.`,
                SUCCESS: (member, role) => `${e.success} **${member}** à bien reçu le rôle **${role}**.`,
            },
            REMOVEROLE: {
                DESCRIPTION: `Permet de retirer un rôle a un membre'.`,
                USAGE: `$removerole <@membre/ID> <@role/ID>`,
                EXAMPLES: `$removerole @Mr¤KayJayDee @amis\n$removerole @Mr¤KayJayDee 123456789`,
                NO_MEMBER: `${e.error} Please mention a member.`,
                NO_ROLE: `${e.error} Merci de mentionner un rôle.`,
                INVALID: `${e.error} Merci de spécifier un rôle valide et de vérifier que mon plus haut rôle est au dessus du rôle que vous voulez ajouter et au dessus du plus haut rôle du membre a qui vous voulez l'ajouter.`,
                HAS_NOT_ROLE: (member, role) => `${e.success} **${member}** n'a pas le rôle **${role}**.`,
                SUCCESS: (member, role) => `${e.success} **${member}** à bien perdu le rôle **${role}**.`,
            },
            SETSERVERNAME: {
                DESCRIPTION: `Permet de changer le nom du serveur.`,
                USAGE: `$setservername <nouveau nom>`,
                EXAMPLES: `$setservername Amandine`,
                NO_ARGS: `${e.error} Merci de spécifier un nouveau nom.`,
                TOO_LONG: `${e.error} Merci de spécifier un nom plus court que 100 caractères.`,
                SUCCESS: (name) => `${e.success} Le serveur a bien été rennommé en **${name}**.`,
            },
            MUTE: {
                DESCRIPTION: `Permet de muter un utilisateur.`,
                USAGE: `$mute <@membre>`,
                EXAMPLES: `$mute @Mr¤KayJayDee`,
                NO_MENTION: `${e.error} Please mention a member.`,
                SUCCESS: (name) => `${e.success} **${name}** à bien été muté.`,
            },
            UNMUTE: {
                DESCRIPTION: `Permet de démuter un utilisateur.`,
                USAGE: `$unmute <@membre>`,
                EXAMPLES: `$unmute @Mr¤KayJayDee`,
                NO_MENTION: `${e.error} Please mention a member.`,
                SUCCESS: (name) => `${e.success} **${name}** à bien été démuté.`,
            },
            MYPERM: {
                DESCRIPTION: `Permet de voir les permissions que vous avez sur le canal ou celles que vos amis ont.`,
                USAGE: `$permissions [@membre]`,
                EXAMPLES: `$permissions @Mr¤KayJayDee\n$permissions`,
                SUCCESS: (name, channel, perms) => `Voici les permissions de **${name}** sur le channel **${channel}**:\n\n${perms}`,
            },
            HASTEBIN: {
                DESCRIPTION: `Permet de coller un lien sur hastebin.`,
                USAGE: `$hastebin <texte>`,
                EXAMPLES: `$hastebin Salut, je suis Amandine, je suis le meilleur des bots.`,
                NO_CONTENT: `${e.error} Merci de spécifier un message.`,
                SUCCESS: (url) => `${e.success} Votre texte a bien été enregistré sur le lien suivant: ${url}.`,
            },
            SERVERICON: {
                DESCRIPTION: `Permet de récupérer l'icone du serveur.`,
                USAGE: `$servericon`,
                EXAMPLES: `$servericon`,
                NO_ICON: `${e.error} Le serveur n'a pas d'icone.`,
            },
            QRCODE: {
                DESCRIPTION: `Permet de générer un code qr.`,
                USAGE: `$qrcode <texte>`,
                EXAMPLES: `$qrcode Salut, je suis Amandine, je suis le meilleur des bots.`,
                NO_MESSAGE: `${e.error} Merci de spécifier un message.`,
            },
            CLEAR: {
                DESCRIPTION: `Permet de nettoyer les message d'un canal.`,
                USAGE: `$clear <quantité/all> [@membre]`,
                EXAMPLES: `$clear 100\n$clear 100 @Mr¤KayJayDee\n$clear all`,
                CANCELLED: `${e.error} La suppression de tout les messages du canal a été annulée.`,
                CONFIRM_ALL: `Merci de confirmer que vous êtes sûr de vouloir supprimer tout les messages du canal, celui-ci sera donc supprimé et cloné. Type \`\`-confirm\`\` to confirm or \`\`cancel\`\` to cancel.`,
                TIMEOUT: `${e.time} Le temp est écoulé, vous n'avez pas validé que vous vouliez supprimmer tout les messages du canal.`,
                SUCCESS_ALL: `${e.success} Le canal a bien été nettoyé.`,
                INVALID: `${e.error} Merci de spécifier une quantité valide.`,
                SUCCESS_USER: (name, amount) => `${e.success} **${amount}** Message de **${name}** ont bien été supprimmés.`,
                SUCCESS: (amount) => `**${amount}** ont bien été suprimmé.`,
            },
            SLOT: {
                DESCRIPTION: `Permet faire tourner la machine a sous.`,
                USAGE: `$slot`,
                EXAMPLES: `$slot`,
                WIN: `Gagné`,
                LOSE: `Perdu`,
            },
            SAY: {
                DESCRIPTION: `Permet d'envoyer un message par le bot.`,
                USAGE: `$say <message>`,
                EXAMPLES: `$say Salut, je suis Amandine, je suis le meilleur des bots.`,
            },
            PASSWORD: {
                DESCRIPTION: `Permet de générer un mot de passe avec les paramètres de votre choix.`,
                USAGE: `$password <longueur>`,
                EXAMPLES: `$password 15`,
                NO_ARG: `${e.error} Merci de spécifier un nombre de caractères.`,
                INVALID: `${e.error} Merci de spécifier un nombre de caractères valide compris entre 5 et 100.`,
                CAPS: `Voulez vous des **majuscules** dans votre mot de passe ?`,
                NUMBER: `Voulez vous des **chiffres** dans votre mot de passe ?`,
                SYMBOLS: `Voulez vous des **symboles** dans votre mot de passe ?`,
                SUCCESS: `${e.success} Votre mot de passe à bien été généré et vous à été envoyé en message privés.`,
            },
        };
    }

    /**
     * The method to get language strings
     * @param {string} term The string or function to look up
     * @param {...*} args Any arguments to pass to the lookup
     * @returns {string|Function}
     */
    get(term, ...args) {
        const value = this.language[term];
        switch (typeof value) {
            case `function`:
                return value(...args);
            default:
                return value;
        }
    }

    getLang() {
        return lang;
    }

    printDate(pdate, isLongDate) {
        let monthNames = [
            `janvier`, `février`, `mars`,
            `avril`, `mai`, `juin`, `juillet`,
            `août`, `septembre`, `octobre`,
            `novembre`, `décembre`
        ];

        let day = pdate.getDate();
        let monthIndex = pdate.getMonth();
        let year = pdate.getFullYear();
        let hour = pdate.getHours() < 10 ? `0` + pdate.getHours() : pdate.getHours();
        let minute = pdate.getMinutes() < 10 ? `0` + pdate.getMinutes() : pdate.getMinutes();

        let thedate = (isLongDate) ? day + ` ` + monthNames[monthIndex] + ` ` + year + ` à ` + hour + `h` + minute :
            day + ` ` + monthNames[monthIndex] + ` ` + year;
        return thedate;
    }

    /**
     * Parse ms and returns a string
     * @param {number} milliseconds The amount of milliseconds
     * @returns The parsed milliseconds
     */
    convertMs(milliseconds) {
        let roundTowardsZero = milliseconds > 0 ? Math.floor : Math.ceil;
        let days = roundTowardsZero(milliseconds / 86400000),
            hours = roundTowardsZero(milliseconds / 3600000) % 24,
            minutes = roundTowardsZero(milliseconds / 60000) % 60,
            seconds = roundTowardsZero(milliseconds / 1000) % 60;
        if (seconds === 0) {
            seconds++;
        }
        let isDays = days > 0,
            isHours = hours > 0,
            isMinutes = minutes > 0;
        let pattern =
            (!isDays ? `` : (isMinutes || isHours) ? `{days} jours, ` : `{days} jours et `) +
            (!isHours ? `` : (isMinutes) ? `{hours} heures, ` : `{hours} heures et `) +
            (!isMinutes ? `` : `{minutes} minutes et `) + (`{seconds} secondes`);
        let sentence = pattern
            .replace(`{duration}`, pattern)
            .replace(`{days}`, days)
            .replace(`{hours}`, hours)
            .replace(`{minutes}`, minutes)
            .replace(`{seconds}`, seconds);
        return sentence;
    }
};